analyse: //span[text()='分析中心']
cancel: //span[text()='取 消']
confirm: //span[text()='确 定']
test_analysis: //div[text()='测试分析-jing.huang']
test_analysis_p: //p[text()='测试分析-jing.huang']
icon: //i[@class='anticon anticon-ellipsis']
release: //a[text()='发布']
account_icon: //img[@alt='avatar']
log_out: //span[text()='退出登录']
all_release: //span[text()='所有发布']
my_analysis: //span[text()='我的分析']
search: //input[@class='ant-input']
search_button: //span[text()='搜索']
test_analysis_design: //p[text()='测试事件分析-自动化']
analysis_name: //div[text()='分析名称']
test_analysis_demo: //p[text()='复制来的测试分析Demo']